CREATE TABLE USERS(
U_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL,
LASTNAME VARCHAR2(30) NOT NULL,
USERNAME VARCHAR2(30) UNIQUE NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL
);

-- PK, FK, NN, U, CHECK, DEFAULT
CREATE TABLE ACCOUNTS ( 
ACC_ID NUMBER PRIMARY KEY,
USER_ID NUMBER NOT NULL,
BALANCE DECIMAL(12,2) NOT NULL,
CONSTRAINT FK_USERID FOREIGN KEY(USER_ID) REFERENCES USERS(U_ID)
);

-- INTRO TO PL SQL = PROCEDURAL LANGUAGE EXTENSION ON SQL
-- SEQUENCE
CREATE SEQUENCE U_SEQ
START WITH 1 
INCREMENT BY 1;
/

-- TRIGGER
CREATE OR REPLACE TRIGGER U_TRIGGER
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT U_SEQ.NEXTVAL INTO :NEW.U_ID FROM DUAL;
END;
/

-- TESTING DOLL
INSERT INTO USERS(FIRSTNAME, LASTNAME, USERNAME, PASSWORD)
VALUES
('Gene', 'Bonds', 'genbo', '123');








-- INTRO TO PL SQL = PROCEDURAL LANGUAGE EXTENSION ON SQL
-- SEQUENCE
CREATE SEQUENCE Acc_SEQ
START WITH 1 
INCREMENT BY 1;
/

-- TRIGGER
CREATE OR REPLACE TRIGGER ACC_TRIGGER
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT ACC_SEQ.NEXTVAL INTO :NEW.U_ID FROM DUAL;
END;