SELECT * FROM employee;

create view employeeshort as select * from employee where employeeid<5;

SELECT * FROM employeeshort;
--NOTE I CHANGED THE ANDREW FILE FROM ONE OF THE CHALLENGES
UPDATE CHINOOK.EMPLOYEE SET LASTNAME = 'BONDS' WHERE FIRSTNAME = 'ANDREW';

DELETE FROM CHINOOK.EMPLOYEE WHERE LASTNAME = 'BONDS';