spring:
  application:
    name: gateway-server
    
server:
  port: 8765    

info:
  component: Edge Server
  description: This is a Zuul demo project
  
zuul:
  prefix: /api #registers a "context" for your app. all services will be found at /api/...
  routes: #tell zuul what services to look for
    account: 
      path: /accounts/**
      serviceId: account-service #needs to match the name of the service you're looking for
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true