CREATE TABLE ERS_REIMBURSEMENT_STATUS(
REIMB_STATUS_ID NUMBER PRIMARY KEY,
REIMB_STATUS VARCHAR2(10) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE(
REIMB_TYPE_ID NUMBER PRIMARY KEY,
REIMB_TYPE VARCHAR2(10) NOT NULL
);

CREATE TABLE ERS_USER_ROLES(
ERS_USER_ROLE_ID NUMBER PRIMARY KEY,
USER_ROLE VARCHAR2(10) NOT NULL
);

CREATE TABLE ERS_USERS(
ERS_USERS_ID NUMBER PRIMARY KEY,
ERS_USERNAME VARCHAR2(50) UNIQUE NOT NULL,
ERS_PASSWORD VARCHAR2(50) NOT NULL,
USER_FIRST_NAME VARCHAR2(100) NOT NULL,
USER_LAST_NAME VARCHAR2(100) NOT NULL,
USER_EMAIL VARCHAR2(150) UNIQUE NOT NULL,
USER_ROLE_ID NUMBER NOT NULL,

CONSTRAINT USER_ROLES_FK FOREIGN KEY(USER_ROLE_ID)
REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID)
);

CREATE TABLE ERS_REIMBURSEMENT(
REIMB_ID NUMBER PRIMARY KEY,
REIMB_AMOUNT NUMBER(19,2) NOT NULL,
REIMB_SUBMITTED TIMESTAMP NOT NULL,
REIMB_RESOLVED TIMESTAMP,
REIMB_DESCRIPTION VARCHAR2(250),
REIMB_RECEIPT BLOB,
REIMB_AUTHOR NUMBER NOT NULL,
REIMB_RESOLVER NUMBER,
REIMB_STATUS_ID NUMBER NOT NULL,
REIMB_TYPE_ID NUMBER NOT NULL,


CONSTRAINT ERS_USERS_FK_AUTH FOREIGN KEY(REIMB_AUTHOR) 
REFERENCES ERS_USERS(ERS_USERS_ID),

CONSTRAINT ERS_USERS_FK_RESLVR FOREIGN KEY(REIMB_RESOLVER)
REFERENCES ERS_USERS(ERS_USERS_ID),

CONSTRAINT ERS_REIMBURSEMENT_STATUS_FK FOREIGN KEY(REIMB_STATUS_ID) 
REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),

CONSTRAINT ERS_REIMBURSEMENT_TYPE_FK FOREIGN KEY(REIMB_TYPE_ID)
REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);


