CREATE TABLE USERS(
U_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL,
LASTNAME VARCHAR2(30) NOT NULL,
USERNAME VARCHAR2(30) UNIQUE NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL
);

-- PK, FK, NN, U, CHECK, DEFAULT
CREATE TABLE ACCOUNTS(
ACC_ID NUMBER PRIMARY KEY,
USER_ID NUMBER NOT NULL,
BALANCE DECIMAL(12,2) NOT NULL,
CONSTRAINT FK_USERID FOREIGN KEY(USER_ID) REFERENCES USERS(U_ID)
);

-- INTRO TO PL/SQL = PROCEDURAL LANGUAGE EXTENSION OF SQL
--  SEQUENCE
CREATE SEQUENCE U_SEQ
START WITH 1000000
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER u_trigger
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT U_SEQ.NEXTVAL INTO :new.u_id FROM DUAL;
END;
/

CREATE SEQUENCE A_SEQ
START WITH 1000000
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER a_trigger
BEFORE INSERT ON ACCOUNTS
FOR EACH ROW
BEGIN
SELECT A_SEQ.NEXTVAL INTO :new.acc_id FROM DUAL;
END;
/

INSERT INTO USERS(FIRSTNAME, LASTNAME, USERNAME, PASSWORD)
VALUES ('Matthew', 'Farr', 'mfarr', 'MS.FarR1701!');

INSERT INTO USERS(FIRSTNAME, LASTNAME, USERNAME, PASSWORD)
VALUES ('Genesis', 'Bonds', 'gbonds', 'p4ssw0rd');

INSERT INTO USERS(FIRSTNAME, LASTNAME, USERNAME, PASSWORD)
VALUES ('Daniel', 'Kelly', 'dkelly', 'MachineGunDaniel');

INSERT INTO ACCOUNTS(USER_ID, BALANCE)
VALUES(1000006, 23000000);

INSERT INTO ACCOUNTS(USER_ID, BALANCE)
VALUES(1000004, 25000);

SELECT * FROM USERS;

SELECT * FROM ACCOUNTS;

SELECT * FROM ACCOUNTS WHERE USER_ID = 1000006;

SELECT BALANCE FROM ACCOUNTS WHERE ACC_ID = 1000030;

UPDATE ACCOUNTS SET BALANCE = 1200 WHERE ACC_ID = 1000025;

COMMIT;

TRUNCATE TABLE USERS;
TRUNCATE TABLE ACCOUNTS;
DROP TABLE ACCOUNTS;
