CREATE TABLE USERS(
U_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL,
LASTNAME VARCHAR2(30) NOT NULL,
USERNAME VARCHAR2(30) UNIQUE NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL
);

select * From users;


--Constraints:
--PK, FK, NN, U, CHECK, DEFAULT
CREATE TABLE ACCOUNTS(
ACC_ID NUMBER PRIMARY KEY,
USER_ID NUMBER NOT NULL,

BALANCE DECIMAL(12,2) NOT NULL,
CONSTRAINT FK_USERID FOREIGN KEY(USER_ID) REFERENCES USERS(U_ID)
);

--intro to PL/SQL = Procedural Language Extension of SQL
-- SEQUENCES
CREATE SEQUENCE U_SEQ
START WITH 1000
INCREMENT BY 1;
/
CREATE SEQUENCE A_SEQ
START WITH 5000
INCREMENT BY 1;
/

--TRIGGER
CREATE OR REPLACE TRIGGER U_TRIGGER
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT U_SEQ.NEXTVAL INTO :NEW.U_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER A_TRIGGER
BEFORE INSERT ON ACCOUNTS
FOR EACH ROW
BEGIN
SELECT A_SEQ.NEXTVAL INTO :NEW.ACC_ID FROM DUAL;
END;
/
-- TESTING DML
INSERT INTO USERS(FIRSTNAME,LASTNAME,USERNAME,PASSWORD)
VALUES
('Genesis','Bonds','genbo','123');