CREATE TABLE USERS(
USER_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL,
LASTNAME VARCHAR2(30) NOT NULL,
USERNAME VARCHAR2(30) UNIQUE NOT NULL,
PASS VARCHAR2(20) NOT NULL
);

-- PK, FK, NOT NULL, UNIQUE, CHECK, DEFAULT
CREATE TABLE ACCOUNTS(
ACC_ID NUMBER PRIMARY KEY,
ACC_TYPE VARCHAR(20) NOT NULL,
USER_ID NUMBER NOT NULL,
BALANCE DECIMAL(12,2) NOT NULL,
CONSTRAINT FK_USERID FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

-- INTRO TO PL/SQL = PROCEDURAL LANGUAGE EXTENSION OF SQL
-- * SEQUENCE
CREATE SEQUENCE U_SEQ
START WITH 1
INCREMENT BY 1;
/
-- * TRIGGER
CREATE OR REPLACE TRIGGER U_TRIGGER
BEFORE INSERT ON USERS
FOR EACH ROW 
BEGIN
SELECT U_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/

-- TESTING DML
INSERT INTO USERS(FIRSTNAME, LASTNAME, USERNAME, PASS)
VALUES ('Bob', 'Dylan', 'bobdylan', 'bobdylan');

SELECT * FROM USERS;
