CREATE TABLE USERS(
U_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR2(30) NOT NULL,
LASTNAME VARCHAR2(30) NOT NULL,
USERNAME VARCHAR2(30) UNIQUE NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL
);

-- PK, FK, NN, U, CHECK, DEFAULT
CREATE TABLE ACCOUNTS
(
  ACC_ID NUMBER PRIMARY KEY,
  USER_ID NUMBER NOT NULL,
  BALANCE DECIMAL(12,2) NOT NULL,
  CONSTRAINT FK_USERID FOREIGN KEY(USER_ID) REFERENCES USERS(U_ID)
);

-- INTRO TO PL/SQL = PROCEDURAL LANGUAGE EXTENSION OF SQL
--  SEQUENCE
CREATE SEQUENCE U_SEQ
START WITH 1
INCREMENT BY 1;

--TRIGGER
CREATE OR REPLACE TRIGGER u_trigger
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT U_SEQ.NEXTVAL INTO :new.U_ID FROM DUAL;
END;

CREATE SEQUENCE ACC_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER a_trigger
BEFORE INSERT ON ACCOUNTS
FOR EACH ROW
BEGIN
SELECT ACC_SEQ.NEXTVAL INTO :new.ACC_ID FROM DUAL;
END;
-- TESTING DML
INSERT INTO ACCOUNTS(USER_ID,BALANCE) VALUES(8,10);
SELECT * FROM ACCOUNTS;

INSERT INTO USERS(FIRSTNAME,LASTNAME,USERNAME,PASSWORD)VALUES('A','B','C','D');
select * from USERS;

select BALANCE FROM ACCOUNTS WHERE USER_ID =3;