CREATE TABLE USERS
(
  U_ID NUMBER PRIMARY KEY,
  FIRSTNAME VARCHAR2(30),
  LASTNAME VARCHAR2(30),
  USERNAME VARCHAR2(30) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(20) NOT NULL
);
--PRIMARY KEY, FOREIGN KEY, UNIQUE, NOT NULL, CHECK, DEFAULT
CREATE TABLE ACCOUNTS
(
  ACC_ID NUMBER PRIMARY KEY,
  USER_ID NUMBER NOT NULL,
  BALANCE DECIMAL(12,2) NOT NULL,
  CONSTRAINT FK_USERID FOREIGN KEY(USER_ID) REFERENCES USERS(U_ID)
);

--INTRO TO PL/SQL = PROCEDURAL LANGUAGE EXTENSION OF SQL
--SEQUENCE
CREATE SEQUENCE U_SEQ
START WITH 1
INCREMENT BY 1;

--Trigger
create or replace TRIGGER U_TRIGGER
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT U_SEQ.NEXTVAL INTO :new.U_ID FROM DUAL;
END;
--testing dml

INSERT INTO USERS(FIRSTNAME,LASTNAME,USERNAME,PASSWORD)VALUES
('TRENT','SMITH','USERNAME','PASSWORD');

SELECT * FROM USERS;