SELECT CHINOOK.ALBUM.TITLE, CHINOOK.ARTIST.ARTISTID
FROM CHINOOK.ALBUM
INNER JOIN CHINOOK.ARTIST ON CHINOOK.ALBUM.ARTISTID = CHINOOK.ARTIST.ARTISTID
INNER JOIN CHINOOK.CUSTOMER ON CHINOOK.ALBUM.ARTISTID = CHINOOK.CUSTOMER.CUSTOMERID
INNER JOIN CHINOOK.EMPLOYEE ON CHINOOK.ALBUM.ARTISTID = CHINOOK.EMPLOYEE.EMPLOYEEID
INNER JOIN CHINOOK.GENRE ON CHINOOK.ALBUM.ARTISTID = CHINOOK.GENRE.GENREID
INNER JOIN CHINOOK.INVOICE ON CHINOOK.ALBUM.ARTISTID = CHINOOK.INVOICE.INVOICEID
INNER JOIN CHINOOK.INVOICELINE ON CHINOOK.ALBUM.ARTISTID = CHINOOK.INVOICELINE.INVOICELINEID
INNER JOIN CHINOOK.MEDIATYPE ON CHINOOK.ALBUM.ARTISTID = CHINOOK.MEDIATYPE.MEDIATYPEID
INNER JOIN CHINOOK.PLAYLIST ON CHINOOK.ALBUM.ARTISTID = CHINOOK.PLAYLIST.PLAYLISTID
INNER JOIN CHINOOK.PLAYLISTTRACK ON CHINOOK.ALBUM.ARTISTID = CHINOOK.PLAYLISTTRACK.PLAYLISTID
INNER JOIN CHINOOK.TRACK ON CHINOOK.ALBUM.ARTISTID = CHINOOK.TRACK.TRACKID;




