--Trent Smith [9:10 AM] 
--2.1
SELECT * FROM CHINOOK.EMPLOYEE;
SELECT * FROM CHINOOK.EMPLOYEE WHERE LASTNAME = 'King';
SELECT * FROM CHINOOK.EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;

--2.2
SELECT * FROM CHINOOK.ALBUM ORDER BY TITLE DESC;
SELECT FIRSTNAME FROM CHINOOK.CUSTOMER ORDER BY CITY ASC;
--2.3
INSERT INTO CHINOOK.GENRE VALUES(27,'KILL LA KILL');
INSERT INTO CHINOOK.GENRE VALUES(26,'trent');

INSERT INTO CHINOOK.EMPLOYEE(EMPLOYEEID,LASTNAME,FIRSTNAME,TITLE)VALUES (9,'TRENT','SMITH','DICTACTOR OF THE WORLD');
INSERT INTO CHINOOK.EMPLOYEE(EMPLOYEEID,LASTNAME,FIRSTNAME,TITLE)VALUES (10,'SON','GOKU','GANGSTA');

--INSERT INTO CHINOOK.CUSTOMER(FIRSTNAME,LASTNAME,COMPANY,EMAIL)VALUES('RICK','SANCHEZ','TRENTS CORP','EXAMPLE');
--INSERT INTO CHINOOK.CUSTOMER(FIRSTNAME,LASTNAME,COMPANY,EMAIL) VALUES('PROFESSOR','FARNSWORTH','TRENTS CORP','EXAMPLE');

--2.4
UPDATE CHINOOK.CUSTOMER SET FIRSTNAME = 'Robert', LASTNAME = 'Walter' WHERE FIRSTNAME ='Aaron' AND LASTNAME = 'Mitchell';
UPDATE CHINOOK.ARTIST SET NAME = 'CCR' WHERE NAME = 'Creedence Clearwater Revival';
SELECT * FROM CHINOOK.ARTIST;
--2.5
SELECT * FROM CHINOOK WHERE ADDRESS LIKE 'T%';

--2.7
alter table CHINOOK.INVOICE DROP CONSTRAINT FK_INVOICECUSTOMERID;
DELETE CHINOOK.CUSTOMER WHERE FIRSTNAME = 'Robert' AND LASTNAME = 'Walter';