create or replace PROCEDURE get_all_tickets(
  cursorParam OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN cursorParam FOR SELECT r.REIMB_ID AS "Ticket ID", u.USER_FIRST_NAME AS "First Name", u.USER_LAST_NAME AS "Last Name", 
  u.USER_EMAIL AS "Email", r.REIMB_AMOUNT AS "Amount", r.REIMB_SUBMITTED AS "Date Submitted",
  r.REIMB_RESOLVED AS "Date Resolved", r.REIMB_DESCRIPTION AS "Description",
  CONCAT(f.USER_FIRST_NAME,CONCAT(', ',f.USER_LAST_NAME)) AS "Resolver",
    s.REIMB_STATUS AS "Status", t.REIMB_TYPE AS "Type"
    FROM ERS_REIMBURSEMENT r 
    INNER JOIN ERS_USERS u ON r.REIMB_AUTHOR=u.ERS_USERS_ID 
    INNER JOIN ERS_REIMBURSEMENT_TYPE t ON r.REIMB_TYPE_ID=t.REIMB_TYPE_ID
    INNER JOIN ERS_REIMBURSEMENT_STATUS s ON r.REIMB_TYPE_ID = s.REIMB_STATUS_ID
    INNER JOIN ERS_USERS f ON f.ERS_USERS_ID=r.REIMB_RESOLVER;
  END;
  
  /
  SELECT r.REIMB_ID AS "Ticket ID", u.USER_FIRST_NAME AS "First Name", u.USER_LAST_NAME AS "Last Name", 
  u.USER_EMAIL AS "Email", r.REIMB_AMOUNT AS "Amount", r.REIMB_SUBMITTED AS "Date Submitted",
  r.REIMB_RESOLVED AS "Date Resolved", r.REIMB_DESCRIPTION AS "Description",
  CONCAT(f.USER_FIRST_NAME,CONCAT(', ',f.USER_LAST_NAME)) AS "Resolver",
    s.REIMB_STATUS AS "Status", t.REIMB_TYPE AS "Type"
    FROM ERS_REIMBURSEMENT r 
    INNER JOIN ERS_USERS u ON r.REIMB_AUTHOR=u.ERS_USERS_ID 
    INNER JOIN ERS_REIMBURSEMENT_TYPE t ON r.REIMB_TYPE_ID=t.REIMB_TYPE_ID
    INNER JOIN ERS_REIMBURSEMENT_STATUS s ON r.REIMB_TYPE_ID = s.REIMB_STATUS_ID
    INNER JOIN ERS_USERS f ON f.ERS_USERS_ID=r.REIMB_RESOLVER;
    
    /
    insert into ERS_REIMBURSEMENT(REIMB_ID,REIMB_AMOUNT, REIMB_SUBMITTED, REIMB_RESOLVED, REIMB_DESCRIPTION,
    REIMB_AUTHOR, REIMB_RESOLVER, REIMB_STATUS_ID, REIMB_TYPE_ID)
    values (11,	50,	'08-DEC-17 09:38:09',	'08-DEC-17 09:38:10',	'testing',		21,	21,	0,	0);
    /
    ALTER SESSION SET NLS_TIMESTAMP_FORMAT='DD-MON-YYYY HH:MI:SS';
    /
    commit;
    /
    ALTER TABLE ERS_USERS ADD FOREIGN KEY (USER_ROLE_ID) REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID);
    /
    commit;
  /
  alter table ERS_USERS add constraint uniqueEmail unique (USER_EMAIL);
  /
  insert into ERS_Users (ERS_USERNAME, ERS_PASSWORD, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_ROLE_ID) values ('asd', 'asd','asd','asd', 'test', '0');