CREATE TABLE USERS(
U_ID NUMBER PRIMARY KEY, 
FIRSTNAME VARCHAR2(30) NOT NULL, 
LASTNAME VARCHAR2(30) NOT NULL, 
USERNAME VARCHAR2(30) UNIQUE NOT NULL, 
PASSWORD VARCHAR2(20) NOT NULL
);

--these are the types of constraints
--PK, FK, NN, U, CHECK, DEFAULT
CREATE TABLE ACCOUNTS(
ACC_ID NUMBER PRIMARY KEY,
USER_ID NUMBER NOT NULL,
BALANCE DECIMAL(12,2) NOT NULL,
CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(U_ID));

--INTRO TO PL/SQL = PROCEDURAL LANGUAGE EXTENSION OF SQL
--SEQUENCES
CREATE SEQUENCE U_SEQ
START WITH 1
INCREMENT BY 1;

--TRIGGER
CREATE OR REPLACE TRIGGER U_TRIGGER
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT U_SEQ.NEXTVAL INTO :NEW.U_ID FROM DUAL;
END;

/

--TESTING DML
INSERT INTO USERS(FIRSTNAME,LASTNAME,USERNAME, PASSWORD)
VALUES
('Marshall', 'Cargle', 'marshall', 'test');

select * from users;