/**
 * 
 */
/*var globaluser = {
	users_id: "",
	username: "",
	password: "",
	firstname: "",
	lastname: "",
	email: "",
	userRoleId: ""	
}*/


window.onload = function(){
	$('#login-submit').on('click', login);
	$("#register-submit").on("click", register);
	/**************************************/
	
	//$('#password-message').hide();
	$('#register-submit').attr("disabled", true);
}

$(document).ready(function(){
	$('#email').keyup(validateEmail);
	$('#username').keyup(validateUsername);
	$('#confirm-password').keyup(validatePassword);
});

function register(){
	var firstname = $('#firstname').val();
	var lastname = $('#lastname').val();
	var username = $('#username').val();
	var password = $('#password').val();
	var confirmPassword = $('#confirm-password').val();
	var email = $('#email').val();
	var selectrole = $('#selectrole').find('.active');
	var userRoleId = selectrole.find('input').attr('id');
	if(firstname == "" || lastname == "" || username == "" || password == "" || 
			confirmPassword == "" || email == "") {
		return alert("Please fill out all the fields in the form.");
	}
	
	/*
	 * 0 for placehold for the id object, that will be autogenerated in database
	 */
	var user = {
			users_id: 0,
			username: username,
			password: password,
			firstname: firstname,
			lastname: lastname,
			email: email,
			userRoleId: userRoleId	
	};
	
	var userJSON = JSON.stringify(user);
	
	var xhr = new XMLHttpRequest();
	xhr.onreadystatechange = function(){
		if(xhr.readyState == 4 && xhr.status==200){
			var user = JSON.parse(xhr.responseText);
			alert("Your account has been created.");
			window.location.replace('index.html');
		}
	};
	
	xhr.open("POST","register", true);
	xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
	xhr.send(userJSON);
}

/*
 * flags to use in validate email, validate username, and validate password
 * set flag to true when the user enters information that does not exist in database
 * for username and password and true for passwordFlag when passwords match
 */
var emailFlag = false;
var usernameFlag = false;
var passwordFlag = false;

function validateEmail(){
	
	var email = $('#email').val();
	var username = $('#username').val();
	var password = $('#password').val();
	var confirmPassword = $('#confirm-password').val();
	var information = [email, ""];
	
	var json = JSON.stringify(information);
	
	var xhr = new XMLHttpRequest();
	xhr.onreadystatechange = function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			var user = JSON.parse(xhr.responseText);
			if(user == null){
				$('#email-message').show();
				$('#email-message').html("Email already exists. Please use another email.");
				$('#register-submit').attr("disabled",true);
				emailFlag = false;
			}
			else{
				//$('#register-submit').attr("disabled",false);
				emailFlag = true;
				if((emailFlag && usernameFlag && passwordFlag) == true) {
					$('#register-submit').attr("disabled", false);
				}
				$('#email-message').hide();
				
			}
		}
	}

	xhr.open("POST", "validateEmail", true);
	xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
	xhr.send(json);
	
}

function validateUsername(){
	
	var email = $('#email').val();
	var username = $('#username').val();
	var password = $('#password').val();
	var confirmPassword = $('#confirm-password').val();
	var information = [username, ""];
	
	var json = JSON.stringify(information);

	var xhr = new XMLHttpRequest();
	xhr.onreadystatechange = function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			var user = JSON.parse(xhr.responseText);
			if(user == null){
				$('#username-message').show();
				$('#username-message').html("Username already exists. Please pick another username.") ;
				$('#register-submit').attr("disabled",true);
				usernameflag = false;
			}
			else{
				//$('#register-submit').attr("disabled",false);
				usernameFlag = true;
				if((emailFlag && usernameFlag && passwordFlag) == true) {
					$('#register-submit').attr("disabled", false);
				}
				$('#username-message').hide();
				
			}
		}
	}

	xhr.open("POST", "validateUsername", true);
	xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
	xhr.send(json);
}


function validatePassword(){
	var email = $('#email').val();
	var username = $('#username').val();
	var password = $('#password').val();
	var confirmPassword = $('#confirm-password').val();
	if(password != confirmPassword){
		$('#password-message').show();
		$('#password-message').html("Password does not match.");
		$('#register-submit').attr("disabled", true);
		passwordFlag = false;
	}
	else{
		passwordFlag = true;
		if((emailFlag && usernameFlag && passwordFlag) == true) {
			$('#register-submit').attr("disabled", false);
		}
		$('#password-message').hide();

	}
	
}

function login(){
	var username = $('#loginusername').val();
	var password = $('#loginpassword').val();

	var information = [username, password];
	
	var json = JSON.stringify(information);
	
	var xhr = new XMLHttpRequest();
	xhr.onreadystatechange = function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			var user = JSON.parse(xhr.responseText);
			/*globaluser.username = user.username;
			globaluser.password = user.password;
			globaluser.firstname = user.firstname;
			globaluser.lastname = user.lastname;
			globaluser.email = user.email;
			globaluser.userRoleId = user.userRoleId;*/
			//$('#message').show();

			if(user == null){
				$('#message').html("Your username or password is incorrect.") ;
			}
			else{
				$('#message').html(`Welcome ${user.firstname}`) ;
				
				// go to manager page if the userRoleId is 1, meaning manager in database
				if(user.userRoleId == 1){
					window.location.replace("manager.html");
				}
				// userRoleId is 2, go to employee page
				else {
					window.location.replace("submitrequest.html");
				}
			}
		}
	}
	
	xhr.open("POST", "login", true);
	xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
	xhr.send(json);
	
}
